---

- name: Create systemd unit file
  ansible.builtin.template:
    src: systemd_play.service.j2
    dest: "/etc/systemd/system/{{ steamengine_project_name }}.service"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - "{{ steamengine_project_name }} restart"
  tags:
    - steamengine_runtime_play2

- name: "Ensure {{ steamengine_project_name }} is running and set to start on boot"
  ansible.builtin.systemd:
    enabled: true
    daemon_reload: true
    name: "{{ steamengine_project_name }}"
  tags:
    - steamengine_runtime_play2
