---

- name: Verify build extension
  ansible.builtin.assert:
    that: (steamengine_build_url | basename | splitext)[1] == ".zip"
  when: steamengine_build_url is defined and steamengine_build_url
  tags:
    - steamengine_deploy_sf
