---

- name: Verify project type
  assert:
    that:
      - "steamengine_project_type is defined"
      - "steamengine_project_type in steamengine_project_types"

- include_tasks: "{{ steamengine_project_type }}/asserts.yml"

- include_tasks: common/install_deps.yml

- include_tasks: common/user.yml

- include_tasks: common/structure.yml

- include_tasks: "{{ steamengine_project_type }}/deploy.yml"
  when: steamengine_build_url is defined

- include_tasks: common/runtime.yml

- include_tasks: "{{ steamengine_project_type }}/runtime.yml"
