---

- name: Download the Project DB dump
  get_url:
    url: "{{ steamengine_db_dump_url }}"
    dest: "{{ steamengine_project_root_path }}/db_dump.zip"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
  register: db_dump
  tags:
    - steamengine_deploy_drupal

- name: Unzip project db dump
  unarchive:
    src: "{{ steamengine_project_root_path }}/db_dump.zip"
    dest: "{{ steamengine_project_root_path }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
    remote_src: yes
    list_files: yes
  register: archive_contents
  tags:
    - steamengine_deploy_drupal

- name: Drupal deploy db
  shell: >
    {{ drush_launcher_path }} -r {{ steamengine_project_root_path_web }} \
    sql:cli < {{ steamengine_project_root_path }}/{{ archive_contents.files[0] }}
  tags:
    - steamengine_deploy_drupal

- name: Delete db dump
  file: 
    path: "{{ steamengine_project_root_path }}/{{ archive_contents.files[0] }}"
    state: absent
  tags:
    - steamengine_deploy_drupal

- name: Delete archive db dump
  file: 
    path: "{{ steamengine_project_root_path }}/db_dump.zip"
    state: absent
  tags:
    - steamengine_deploy_drupal

- name: Update the database
  command: "{{ drush_launcher_path }} -r {{ steamengine_project_root_path_web }} -vvv updatedb -y"
  register: output
  tags:
    - steamengine_deploy_drupal
