---

- name: Remove settings
  file:
    path: "{{ steamengine_project_root_path_web }}/web/sites/default/settings.php"
    state: absent
  tags:
    - steamengine_deploy_drupal

- name: Install Drupal with drush.
  shell: >
    {{ steamengine_drupal_drush_path }} site-install standard -y  \
    --site-name="{{ steamengine_drupal_site_name }}" \
    --account-name="{{ steamengine_drupal_admin_name }}" \
    --account-pass="{{ steamengine_drupal_admin_password }}" \
    --locale="{{ steamengine_drupal_site_locale }}" \
    --db-url="mysql://{{ steamengine_drupal_mysql_user }}:{{ steamengine_drupal_mysql_password }}@{{ steamengine_drupal_mysql_host }}:{{ steamengine_drupal_mysql_port }}/{{ steamengine_drupal_mysql_name }}"
  args:
    chdir: "{{ steamengine_project_root_path_web }}"
  tags:
    - steamengine_deploy_drupal
