---

- name: Remove settings link
  file:
    path: "{{ steamengine_project_root_path_web }}/web/sites/default/settings.php"
    state: absent
  tags:
    - steamengine_deploy_drupal

- name: Remove settings 
  file:
    path: "{{ steamengine_conf_path }}/settings.php"
    state: absent
  tags:
    - steamengine_deploy_drupal

- name: Install Drupal with drush.
  command: >
    {{ drush_launcher_path }} site-install standard -y  \
    -r {{ steamengine_project_root_path_web }} \
    --site-name="{{ steamengine_drupal_install_site_name }}" \
    --account-name="{{ steamengine_drupal_install_admin_name }}" \
    --account-pass="{{ steamengine_drupal_install_admin_password }}" \
    --locale="{{ steamengine_drupal_install_site_locale }}" \
    --db-url="{{ steamengine_drupal_database_url }}"
  tags:
    - steamengine_deploy_drupal

- name: "Move setting files to {{ steamengine_conf_path }}"
  command: "mv {{ steamengine_project_root_path_web }}/web/sites/default/settings.php {{ steamengine_conf_path }}/settings.php"
  tags:
    - steamengine_deploy_drupal

- name: Create configuration link
  file:
    state: link
    src: "{{ steamengine_conf_path }}/settings.php"
    dest: "{{ steamengine_project_root_path_web }}/web/sites/default/settings.php"
  tags:
    - steamengine_deploy_drupal

- name: Check if there is existing config
  stat:
    path: "{{ steamengine_project_root_path_web }}/config"
  register: config_dir
  tags:
    - steamengine_deploy_drupal

- name: Drupal import config
  command: >
    {{ drush_launcher_path }} -r {{ steamengine_project_root_path_web }} \
    config-import -y --source={{ steamengine_project_root_path_web }}/config
  when: config_dir.stat.exists and new_build_to_deploy
  tags:
    - steamengine_deploy_drupal
