---

- name: Remove settings link
  file:
    path: "{{ steamengine_project_root_path_web }}/web/sites/default/settings.php"
    state: absent
  tags:
    - steamengine_deploy_drupal

- name: Remove settings
  file:
    path: "{{ steamengine_conf_path }}/settings.php"
    state: absent
  tags:
    - steamengine_deploy_drupal

- name: Install Drupal with drush.
  command: >
    {{ steamengine_drush_launcher_path }} site-install {{ steamengine_drupal_install_profile }} -y  \
    -r {{ steamengine_project_root_path_web }} \
    --site-name="{{ steamengine_drupal_install_site_name }}" \
    --site-mail="{{ steamengine_drupal_install_site_mail }}" \
    --account-name="{{ steamengine_drupal_install_admin_name }}" \
    --account-pass="{{ steamengine_drupal_install_admin_password }}" \
    --account-mail="{{ steamengine_drupal_install_account_mail }}" \
    --locale="{{ steamengine_drupal_install_site_locale }}" \
    --db-url="{{ steamengine_drupal_install_database_url }}" \
    --config-dir="{{ steamengine_drupal_install_config_dir }}"
  when: new_deploy and steamengine_drupal_install_from_drush
  tags:
    - steamengine_deploy_drupal

- name: "Move setting files to {{ steamengine_conf_path }}"
  command: "mv {{ steamengine_project_root_path_web }}/web/sites/default/settings.php {{ steamengine_conf_path }}/settings.php"
  when: new_deploy and steamengine_drupal_install_from_drush
  tags:
    - steamengine_deploy_drupal

- name: Create configuration link
  file:
    state: link
    src: "{{ steamengine_conf_path }}/settings.php"
    dest: "{{ steamengine_project_root_path_web }}/web/sites/default/settings.php"
  tags:
    - steamengine_deploy_drupal
