---

- name: Create project folder structure (5)
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: 0770
  with_items:
    - "{{ steamengine_sf4_global_logs_path }}"

- name: Create project folder structure (6)
  file:
    src: "{{ steamengine_sf4_link_directory_path }}/{{ item.key }}"
    state: directory
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: 0770
  with_items: "{{ steamengine_sf4_link_directory }}"
