---

- name: Unarchive build
  ansible.builtin.unarchive:
    src: "{{ archive_path }}"
    dest: "{{ dest_path }}"
    remote_src: true
    list_files: true
  register: front_static_unzip_output

- name: Registering all existing files
  ansible.builtin.find:
    paths: "{{ dest_path }}"
    recurse: true
  register: front_static_find_output

- name: Registering new and old files
  ansible.builtin.set_fact:
    front_static_old_files: "{{ front_static_find_output.files | map(attribute='path') | list | map('regex_replace', dest_path + '/', '' ) | list }}"
    front_static_new_files: "{{ front_static_unzip_output.files }}"

- name: Remove old static files
  ansible.builtin.file:
    path: "{{ dest_path }}/{{ item }}"
    state: absent
  with_items: "{{ front_static_old_files | difference(front_static_new_files) }}"
