---

- name: Create systemd unit file
  template:
    src: systemd_tomcat7.service.j2
    dest: "/etc/systemd/system/{{ steamengine_project_name }}.service"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - "{{ steamengine_project_name }} restart"
  tags:
    - steamengine_runtime_tomcat7

- name: "Add www-data in {{ steamengine_app_user }} group"
  user:
    name: www-data
    groups: "{{ steamengine_app_user }}"
    append: true
  tags:
    - steamengine_runtime_tomcat7

- name: "Ensure {{ steamengine_project_name }} is running and set to start on boot"
  systemd:
    enabled: true
    daemon_reload: true
    name: "{{ steamengine_project_name }}"
  tags:
    - steamengine_runtime_tomcat7
