---

- name: Create systemd unit file
  template:
    src: systemd_tomcat7.service.j2
    dest: "/etc/systemd/system/{{ steamengine_project_name }}.service"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - "steamengine restart"

- name: "Ensure {{ steamengine_project_name }} is running and set to start on boot"
  systemd:
    state: started
    enabled: true
    daemon_reload: true
    name: "{{ steamengine_project_name }}"
