---

- name: Create configuration file
  copy:
    content: |
      # This file is managed by Ansible, all changes will be lost.
      {{ steamengine_project_configuration | to_nice_yaml }}
    dest: "{{ steamengine_conf_path }}/project_env_conf.yml"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rw,g=r,o=
  notify:
    - "steamengine restart"
  tags:
    - steamengine_deploy_springboot

- name: Create external configuration file
  template:
    src: "{{ steamengine_project_configuration_template_path }}"
    dest: "{{ steamengine_conf_path }}/project_env_conf.yml"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rw,g=r,o=
  when: steamengine_project_configuration_template_path is defined
  notify:
    - "steamengine restart"
  tags:
    - steamengine_deploy_springboot

- name: "Download build {{ steamengine_build_url }}"
  get_url:
    url: "{{ steamengine_build_url }}"
    dest: "{{ steamengine_project_root_path }}/project.jar"
    checksum: "{{ steamengine_build_checksum }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: 0750
  notify:
    - "steamengine restart"
  tags:
    - steamengine_deploy_springboot
