---

### MySQL Database

- name: "Download the MySQL Database inside MySQL Container"
  get_url:
    url: "{{ steamengine_db_dump_url }}"
    dest: "{{ steamengine_project_root_path }}/db_dump.zip"
  register: get_url_db
  when: steamengine_db_dump_url
  tags:
    - steamengine_deploy_drupal8

- name: "Is there a new database: {{ get_url_db.changed }}"
  set_fact:
    new_db_to_deploy: get_url_db.changed
  when: steamengine_db_dump_url
  tags:
    - steamengine_deploy_drupal8

- name: "Unzip the database"
  unarchive:
    src: "{{ steamengine_project_root_path }}/db_dump.zip"
    dest: "{{ steamengine_project_root_path }}/db_dump.sql"
  when: steamengine_db_dump_url
  tags:
    - steamengine_deploy_drupal8

- name: Drupal deploy db
  shell: "drush sql:cli < /db/db_dump.sql"
  args:
    chdir: "{{ steamengine_project_root_path_web }}"
  when: steamengine_db_dump_url
  tags:
    - steamengine_deploy_drupal8

- name: Update the database
  shell: "drush updatedb -y"
  args:
    chdir: "{{ steamengine_project_root_path_web }}"
  when: steamengine_db_dump_url
  tags:
    - steamengine_deploy_drupal8

- name: Update settings


### Build

- name: "Download build {{ steamengine_build_url }}"
  get_url:
    url: "{{ steamengine_build_url }}"
    dest: "{{ steamengine_project_root_path }}/project.zip"
    checksum: "{{ steamengine_build_checksum }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
    headers: "{{ steamengine_build_url_headers }}"
    validate_certs: "{{ steamengine_build_url_validate_certs }}"
  notify:
    - "{{ steamengine_project_name }} restart"
  register: get_url_build
  when: steamengine_build_url
  tags:
    - steamengine_deploy_drupal8

- name: "Is there a new build: {{ get_url_build.changed }}"
  set_fact:
    new_build_to_deploy: get_url_build.changed
  when: steamengine_build_url
  tags:
    - steamengine_deploy_drupal8

- name: Clean drupal cache
  shell: "drush cache:rebuild"
  args:
    chdir: "{{ steamengine_project_root_path_web }}"
  tags:
    - steamengine_deploy_drupal8
