---
- name: Converge
  hosts: instance
  become: true
  roles:
    - role: geerlingguy.nodejs
      vars:
        nodejs_version: "16.x"
        nodejs_install_npm_user: root
        nodejs_npm_global_packages:
          - name: pm2
            version: 5.2.0
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        steamengine_project_name: test_nodejs
        steamengine_project_type: nodejs
        steamengine_build_url: https://delivery.steamulo.org/SteamEngineV2_tests/nodejs-express-build.zip
        steamengine_build_checksum: sha1:5ca5bebc8f3b770358732c90b20b94b710158d55
        steamengine_persistent_directories:
          - path: "certs"
            symlink_src: "project_root/www/certs"
          - path: "protected_upload/images"
            symlink_src: "project_root/www/images"
          - path: "protected_upload/gifs"
            symlink_src: "project_root/www/gifs"
        steamengine_project_configuration:
          PORT: 3300
