---
- name: Converge
  hosts: instance
  become: true
  roles:
    - role: lean_delivery.java
      vars:
        transport: web
        transport_web: https://delivery.steamulo.org/oracle-java/jdk-8u211-linux-x64.tar.gz
    - role: steamulo.steamengine
      vars:
        steamengine_project_name: play2_test
        steamengine_project_type: play
        steamengine_build_url: https://delivery.steamulo.org/SteamEngineV2_tests/play2_test.zip
        steamengine_build_checksum: sha1:1647db0e96df9da3a3ecdc60c425b720a646a670
        steamengine_project_configuration_base_name: "application"
        steamengine_project_configuration:
          play:
            http:
              secret:
                key: "azfafzefezfbzelgbzebfganfdmazofnzmoenfoazen"
