---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: geerlingguy/ubuntu1804
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: tomcat7
verifier:
  name: testinfra
  lint:
    name: flake8
