---

# Setup checksum verification
- name: Ensure non-empty checksum
  set_fact:
    empty_checksum_check: "{{ (steamengine_build_checksum == '') | ternary('sha1:1', steamengine_build_checksum) }}"

- name: Confirm the verification of the checksum
  set_fact:
    checksum_verified: "{{ steamengine_skip_checksum | ternary('', empty_checksum_check) }}"


- name: "Download build {{ steamengine_build_url }}"
  ansible.builtin.get_url:
    url: "{{ steamengine_build_url }}"
    dest: "{{ steamengine_project_root_path }}/project.zip"
    checksum: "{{ checksum_verified }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
    headers: "{{ steamengine_build_url_headers }}"
    validate_certs: "{{ steamengine_build_url_validate_certs }}"
  register: get_url_build
  tags:
    - steamengine_deploy_static

- name: Create www directory
  ansible.builtin.file:
    path: "{{ steamengine_project_root_path_web }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
    state: directory
  tags:
    - steamengine_deploy_static

- name: Update www directory
  include_tasks: include/update_from_archive.yml
  vars:
    archive_path: "{{ steamengine_project_root_path }}/project.zip"
    dest_path: "{{ steamengine_project_root_path_web }}"
  when: get_url_build.changed
  args:
    apply:
      tags:
        - steamengine_deploy
        - steamengine_deploy_static
  tags:
    - steamengine_deploy_static

- name: "Add read permission for {{ steamengine_app_user }}"
  ansible.builtin.file:
    path: "{{ steamengine_project_root_path_web }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    recurse: true
    mode: u=rwx,g=rx,o=
  tags:
    - steamengine_deploy_static
