---

- name: "Add www-data in {{ steamengine_app_user }} group"
  user:
    name: www-data
    groups: "{{ steamengine_app_user }}"
    append: true
  tags:
    - steamengine_runtime
    - steamengine_runtime_static
