---

- name: Verify build extension
  assert:
    that: (steamengine_build_url | basename | splitext)[1] == ".war"
  when: steamengine_build_url is defined and steamengine_build_url
  tags:
    - steamengine_deploy_tomcat

- name: Verify conf sources
  assert:
    that: steamengine_project_configuration_template_path is undefined or steamengine_project_configuration is undefined
  tags:
    - steamengine_deploy_tomcat

- name: Verify tomcat version
  assert:
    that: steamengine_tomcat_major_version == "7" or steamengine_tomcat_major_version == "9"
  tags:
    - steamengine_deploy_tomcat
