---

- name: "Download build {{ steamengine_build_url }}"
  get_url:
    url: "{{ steamengine_build_url }}"
    dest: "{{ steamengine_project_root_path }}/project.zip"
    checksum: "{{ steamengine_build_sha1_checksum }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
  register: get_url_build

- name: Create www directory
  file:
    path: "{{ steamengine_project_root_path_web }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rx,o=
    state: directory

- name: Create pm2 directory
  file:
    path: "{{ steamengine_project_root_path }}/pm2"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    mode: u=rwx,g=rwx,o=
    state: directory

- name: Update www directory
  import_tasks: include/update_from_zip.yml
  vars:
    zip_path: "{{ steamengine_project_root_path }}/project.zip"
    dest_path: "{{ steamengine_project_root_path_web }}"
  when: get_url_build.changed

- name: "Add read permission for {{ steamengine_app_user }}"
  file:
    path: "{{ steamengine_project_root_path_web }}"
    owner: "{{ steamengine_project_user }}"
    group: "{{ steamengine_app_user }}"
    recurse: true
    mode: u=rwx,g=rx,o=
