- name: Converge
  hosts: instance
  become: true

  pre_tasks:
    - include_tasks: "../resources/setup_{{ ansible_os_family | lower }}.yml"

    - name: Add mysql-client
      apt:
        name: mysql-client
        state: present

    - name: Add ppa:ondrej/php repository
      apt_repository:
        repo: ppa:ondrej/php
      when: ansible_os_family == 'Debian'
    - name: Add mysql repository
      apt_repository:
        repo: ppa:ondrej/php
      when: ansible_os_family == 'Debian'

    - name: Add remi-php74 repository
      yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
      when: ansible_os_family == 'RedHat'

  roles:
    - role: geerlingguy.php
      vars:
        php_enablerepo: "remi-php74"
        php_default_version_debian: "7.4"
        php_install_recommends: false
        php_enable_php_fpm: true
        php_fpm_listen: "/var/run/php/php7.4-fpm.sock"
        php_webserver_daemon: "nginx"
        php_date_timezone: "Europe/Paris"
        php_expose_php: Off
        php_packages_extra:
          - php7.4-mysql
    - role: geerlingguy.git
    - role: geerlingguy.composer
      vars:
        composer_path: /usr/local/bin/composer
    - role: geerlingguy.drush
    - role: geerlingguy.nginx
      vars:
        nginx_ppa_use: true
        nginx_remove_default_vhost: true
        nginx_worker_processes: "{{ ansible_processor_vcpus|default(ansible_processor_count) }}"
        nginx_vhosts:
          - listen: "80"
            server_name: "localhost"
            root: /drupal/project_root/web
            template: "{{ playbook_dir }}/../../templates/drupal8_vhost.j2"
        tags:
          - steamengine_nginx
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        steamengine_project_name: drupal
        steamengine_project_type: drupal8
        steamengine_drupal_hash_salt: drupal
        steamengine_drupal_mysql_host: 172.17.0.1
        steamengine_drupal_mysql_port: 4806
        steamengine_drupal_mysql_db_name: "drupal"
        steamengine_drupal_mysql_db_user: "drupal"
        steamengine_drupal_mysql_db_password: "drupal"
