- name: Converge
  hosts: instance
  become: true

  pre_tasks:
    - include_tasks: "../resources/setup_{{ ansible_os_family | lower }}.yml"

    - name: Add ppa:ondrej/php repository
      apt_repository:
        repo: ppa:ondrej/php
      when: ansible_os_family == 'Debian'

    - name: Add remi-php74 repository
      yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present
      when: ansible_os_family == 'RedHat'

  roles:
    - role: steamulo.mysql
      become: yes
      vars:
        mysql_databases:
        - name: "drupal"
        mysql_users:
        - name: "drupal"
          host: "%"
          password: "drupal"
          priv: "drupal.*:ALL,GRANT"
    - role: geerlingguy.php
      vars:
        php_enablerepo: "remi-php74"
        php_default_version_debian: "7.4"
        php_install_recommends: false
        php_enable_php_fpm: true
        php_webserver_daemon: "nginx"
        php_date_timezone: "Europe/Paris"
        php_expose_php: Off
        php_packages_extra: "{{ (ansible_os_family == 'Debian') | ternary(['php7.4-mysql'], ['php-mysql']) }}"
    - role: geerlingguy.git
    - role: geerlingguy.composer
      vars:
        composer_path: /usr/local/bin/composer
    - role: geerlingguy.drush
    - role: geerlingguy.nginx
      vars:
        nginx_ppa_use: true
        nginx_remove_default_vhost: true
        nginx_worker_processes: "{{ ansible_processor_vcpus|default(ansible_processor_count) }}"
        nginx_vhosts:
          - listen: "80"
            server_name: "localhost"
            root: /drupal/project_root/www/web
            extra_parameters: |
              client_max_body_size 4096M;

              location / {
                  try_files $uri /index.php?$query_string;
              }

              location @rewrite {
                rewrite ^ /index.php;
              }

              location ~ '\.php$|^/update.php' {
                fastcgi_split_path_info ^(.+?\.php)(|/.*)$;
                try_files $fastcgi_script_name =404;
                include fastcgi_params;
                fastcgi_param HTTP_PROXY "";
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param PATH_INFO $fastcgi_path_info;
                fastcgi_param QUERY_STRING $query_string;
                fastcgi_intercept_errors on;
                fastcgi_pass 127.0.0.1:9000;
              }

              location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
                try_files $uri @rewrite;
                expires max;
                log_not_found off;
              }

              location ~ ^/sites/.*/files/styles/ {
                try_files $uri @rewrite;
              }

              location ~ ^(/[a-z\-]+)?/system/files/ {
                try_files $uri /index.php?$query_string;
              }

              if ($request_uri ~* "^(.*/)index\.php/(.*)") {
                return 307 $1$2;
              }

              error_log /var/log/nginx/project_error.log;
              access_log /var/log/nginx/project_access.log;
        tags:
          - steamengine_nginx
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        steamengine_project_name: drupal
        steamengine_project_type: drupal
        steamengine_drupal_install_from_drush: true
        steamengine_drupal_install_from_db_dump: false
        steamengine_db_dump_url: https://delivery.steamulo.org/SteamEngineV2_tests/db_dump_drupal_8.zip
        steamengine_build_url: https://delivery.steamulo.org/SteamEngineV2_tests/drupal_8.zip
        steamengine_build_checksum: sha1:a354cceb222ef776644394f72f3f9278265ba6ae

#Drupal 9: https://delivery.steamulo.org/SteamEngineV2_tests/drupal_9.zip
#Drupal 9 : d6d2a3e93857b97b6c8b914b28e9a3766fe56bf8