- name: Converge
  hosts: instance
  become: true

  pre_tasks:
    - include_tasks: "../resources/setup_{{ ansible_os_family | lower }}.yml"

    - name: Add mysql-client
      apt:
        name: mysql-client
        state: present

    - name: Add ppa:ondrej/php repository
      apt_repository:
        repo: ppa:ondrej/php
      when: ansible_os_family == 'Debian'
    - name: Add mysql repository
      apt_repository:
        repo: ppa:ondrej/php
      when: ansible_os_family == 'Debian'

    - name: Add remi-php74 repository
      yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
      when: ansible_os_family == 'RedHat'

  roles:
    - role: geerlingguy.php
      vars:
        php_enablerepo: "remi-php74"
        php_default_version_debian: "7.4"
        php_install_recommends: false
        php_enable_php_fpm: true
        php_webserver_daemon: "nginx"
        php_date_timezone: "Europe/Paris"
        php_expose_php: Off
    - role: geerlingguy.git
    - role: geerlingguy.composer
      vars:
        composer_path: /usr/local/bin/composer
    - role: geerlingguy.drush
    - role: geerlingguy.drupal
      vars:
        drupal_deploy: false
        drupal_deploy_dir: "/test_drupal/project_root/www"
        drupal_build_makefile: false
        drupal_build_composer: false
        drupal_install_site: false

        drupal_build_composer_project: true
        drupal_composer_project_package: "drupal/recommended-project:^8"
        drupal_composer_project_options: "--prefer-dist --stability dev --no-interaction"

        drupal_core_path: "{{ drupal_deploy_dir }}/web"
        drupal_core_owner: "{{ ansible_ssh_user | default(ansible_env.SUDO_USER, true) | default(ansible_env.USER, true) | default(ansible_user_id) }}"
        drupal_core_owner_become: false
        drupal_db_name: "{{ drupal_mysql_db_name }}"
        drupal_db_user: "{{ drupal_mysql_db_user }}"
        drupal_db_password: "{{ drupal_mysql_db_password }}"
        drupal_db_host: "172.17.0.1:4806"
    - role: geerlingguy.nginx
      vars:
        nginx_ppa_use: true
        nginx_remove_default_vhost: true
        nginx_worker_processes: "{{ ansible_processor_vcpus|default(ansible_processor_count) }}"
        nginx_vhosts:
          - listen: "80"
            server_name: "localhost"
            index: "/"
            extra_parameters: |
              root /test_drupal/project_root/www/web;

              location / {
                  # Trying to upload the file, switch to Apache in case of failure
                  try_files $uri @drupal;
                }

                location ~ \.php$ {
                  fastcgi_pass   127.0.0.1:9000;
                  fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
                  include        fastcgi_params;
                }

                location @drupal {
                  fastcgi_pass 127.0.0.1:9000;
                  fastcgi_index  index.php;
                  fastcgi_read_timeout 600;
                  fastcgi_param  SCRIPT_FILENAME      $document_root/index.php;
                  fastcgi_param  QUERY_STRING         q=$uri&$args;
                  fastcgi_param  REQUEST_METHOD       $request_method;
                  fastcgi_param  CONTENT_TYPE         $content_type;
                  fastcgi_param  CONTENT_LENGTH       $content_length;
                  fastcgi_param  REDIRECT_STATUS      200;
                  fastcgi_param  SCRIPT_NAME          /index.php;
                  fastcgi_param  REQUEST_URI          $request_uri;
                  fastcgi_param  DOCUMENT_URI         $document_uri;
                  fastcgi_param  DOCUMENT_ROOT        $document_root;
                  fastcgi_param  SERVER_PROTOCOL      $server_protocol;
                  fastcgi_param  GATEWAY_INTERFACE    CGI/1.1;
                  fastcgi_param  SERVER_SOFTWARE      nginx/$nginx_version;
                  fastcgi_param  REMOTE_ADDR          $remote_addr;
                  fastcgi_param  REMOTE_PORT          $remote_port;
                  fastcgi_param  SERVER_ADDR          $server_addr;
                  fastcgi_param  SERVER_PORT          $server_port;
                  fastcgi_param  SERVER_NAME          $server_name;
                }

    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        steamengine_project_name: test_drupal
        steamengine_project_type: drupal8
        steamengine_build_url:
        steamengine_build_checksum: sha1:5ca5bebc8f3b770358732c90b20b94b710158d55
        steamengine_project_configuration:

